### ISSUE TITLE
Release v1.0.1 not available in TF registry

### ISSUE THREAD

**Issue by pawelaugustyn** [DataDome/terraform-provider-datadome#10]
Hello there! ✋🏻 

In the beginning, thanks for fixing an incomplete `v1.0.1` release!

I wanted to update my Terraform code to use the latest version, but I noticed that the mentioned release is not published to the Terraform Registry. [Link to the latest version](https://registry.terraform.io/providers/DataDome/datadome/latest) still points to the `v1.0.0` version which is currently the only available one.

Can you fix that?

**Comment by pawelaugustyn** [comment]
@emmanuelCarre FYI

**Comment by emmanuelCarre** [comment]
Hi,

Sorry for this. We encounter an issue to publish the provider and we contacted Terraform registry support to fix that.
I will publish it as soon as possible and keep you informed.
