### ISSUE TITLE
Incomplete Release v1.0.1

### ISSUE THREAD

**Issue by pawelaugustyn** [DataDome/terraform-provider-datadome#8]
Hi,

I see that release `v1.0.1` is incomplete as release workflow failed on building some of the artifacts.

Can you take a look at that? Thanks!

**Comment by pawelaugustyn** [comment]
@gilleswalbrou fyi

**Comment by emmanuelCarre** [comment]
Hello @pawelaugustyn,

Sorry for this delay.  As I say in #11, we are still discussing with terraform registry support to identify what is wrong with release [v1.0.1](https://github.com/DataDome/terraform-provider-datadome/releases/tag/v1.0.1).
I same time, I updated actions from our Github workflow and use a new GPG key and try to publish an RC for test and it works. So we create a new release [v1.0.2](https://github.com/DataDome/terraform-provider-datadome/releases/tag/v1.0.2) with only CI change: https://github.com/DataDome/terraform-provider-datadome/compare/v1.0.1%E2%80%A6v1.0.2.

The provider is available here: https://registry.terraform.io/providers/DataDome/datadome/1.0.2

Pay attention, `v1.0.2-rc1` and `v1.0.2-rc.1` appear newer than `v1.0.2`. Please, don't use latest and set provider version :pray:  I have to check is point.

**Comment by pawelaugustyn** [comment]
Hi @emmanuelCarre 
I confirm `v1.0.2` works properly. Actually, I didn't set my provider configuration to use `1.0.2` explicitly. Instead, I use `~> 1.0.0` as the version constraint and `1.0.2` gets picked up correctly.

Thanks for publishing this new release to the registry!

**Comment by emmanuelCarre** [comment]
Hello,

Unfortunately, we didn't found with Terraform support a proper solution to fix that. As we can use version `1.0.2` as workaround I close this issue.

Thank you for your patience and feedbacks. Feel free to open new issue needed.
